//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMNOTICE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MAX_THREAD_COUNT {
            get {
                return ((int)(this["MAX_THREAD_COUNT"]));
            }
            set {
                this["MAX_THREAD_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int EACH_TIME_SELECT_TOP_COUNT {
            get {
                return ((int)(this["EACH_TIME_SELECT_TOP_COUNT"]));
            }
            set {
                this["EACH_TIME_SELECT_TOP_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LOOP_LOAD_DATA_THRESHOLD {
            get {
                return ((int)(this["LOOP_LOAD_DATA_THRESHOLD"]));
            }
            set {
                this["LOOP_LOAD_DATA_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1000.0;")]
        public string TASK_CRONS_CONFIG_STRING {
            get {
                return ((string)(this["TASK_CRONS_CONFIG_STRING"]));
            }
            set {
                this["TASK_CRONS_CONFIG_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int CLEAR_LOG_THRESHOLD {
            get {
                return ((int)(this["CLEAR_LOG_THRESHOLD"]));
            }
            set {
                this["CLEAR_LOG_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENCRYPT_IP_ADDRESS {
            get {
                return ((string)(this["ENCRYPT_IP_ADDRESS"]));
            }
            set {
                this["ENCRYPT_IP_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CLIENT_ID {
            get {
                return ((string)(this["CLIENT_ID"]));
            }
            set {
                this["CLIENT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NEED_CHECK_FROM_DATABASE {
            get {
                return ((bool)(this["NEED_CHECK_FROM_DATABASE"]));
            }
            set {
                this["NEED_CHECK_FROM_DATABASE"] = value;
            }
        }
    }
}
