//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JmPay.PayChannelMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int INTERVAL_NO_ORDER_APP {
            get {
                return ((int)(this["INTERVAL_NO_ORDER_APP"]));
            }
            set {
                this["INTERVAL_NO_ORDER_APP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int INTERVAL_APP_PAY_SUCCESS_ABNORMAL {
            get {
                return ((int)(this["INTERVAL_APP_PAY_SUCCESS_ABNORMAL"]));
            }
            set {
                this["INTERVAL_APP_PAY_SUCCESS_ABNORMAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int INTERVAL_ORDER_PAY_ABNORMAL {
            get {
                return ((int)(this["INTERVAL_ORDER_PAY_ABNORMAL"]));
            }
            set {
                this["INTERVAL_ORDER_PAY_ABNORMAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TIMESPAN_NO_ORDER_APP_SEND_MESSAGE {
            get {
                return ((int)(this["TIMESPAN_NO_ORDER_APP_SEND_MESSAGE"]));
            }
            set {
                this["TIMESPAN_NO_ORDER_APP_SEND_MESSAGE"] = value;
            }
        }
    }
}
